INSERT INTO DELTAPLUS_USER_TEST VALUES (NULL, 'gerardo.garza@softtek', 'gerardo', '123456', 'Gerardo', 'Garza', 'Softtek', 1, sysdate(), sysdate());

select * from DELTAPLUS_USER_TEST;

SELECT * FROM DELTAPLUS_PRODUCT_TEST WHERE ID = 1 AND IS_DELETED = 0 LIMIT 20;

SELECT COUNT(*) totalCount FROM DELTAPLUS_PRODUCT_TEST WHERE ID = '1' AND IS_DELETED = 0;

SELECT P.ID, P.PRODUCT, P.SERIAL, P.USERNAME, P.PROD_DATE, P.START_DATE, P.SAV1, P.SAV2, P.SAV3, P.SAV4, P.SAV5, CONCAT(U.FIRST_NAME, ' ', U.LAST_NAME) USER_NAME FROM DELTAPLUS_PRODUCT_TEST P,DELTAPLUS_USER_TEST U WHERE P.DELTA_USER_ID = U.USER_ID AND P.IS_DELETED = 0 LIMIT 20;

INSERT INTO DELTAPLUS_PRODUCT_TEST VALUES (NULL, 'Glooves', 'GL-45424', 'Gerardo', '2014-12-20', '2015-02-2', null, null, null, null, null, 0, sysdate(), sysdate(), 1);

SELECT COUNT(*) totalCount FROM DELTAPLUS_PRODUCT_TEST WHERE IS_DELETED = 0;

SELECT * FROM DELTAPLUS_USER_TEST LIMIT 20;

INSERT INTO DELTAPLUS_USER_TEST(USER_ID, EMAIL, PASSWORD, FIRST_NAME, LAST_NAME, COMPANY, LOGIN, USER_TYPE) VALUES(NULL, 'manny_pacquiao@box.com', 'pacman', 'Manny', 'Pacquiao', 'Box', 'pacman', 0);

SELECT USER_ID, CONCAT(FIRST_NAME, ' ', LAST_NAME) name, USER_TYPE FROM DELTAPLUS_USER_TEST WHERE LOGIN = 'GERARDO' AND PASSWORD = '123456' ORDER BY USER_ID DESC;